[package]
name = "advent"
version = "0.1.0"
edition = "2021"

[dependencies]
utilities = { path = "../utilities" }
itertools = { workspace = true }
rayon = { workspace = true }

[[bin]]
name = "y24d01"
path = "src/bin/2024/y24d01.rs"